//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinalHorus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients_Packages
    {
        public int id_client { get; set; }
        public int id_domain { get; set; }
        public int id_package { get; set; }
        public string payment_method { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Domain Domain { get; set; }
        public virtual Package Package { get; set; }
    }
}
