//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinalHorus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectFinalHorus20180610020451_dbEntities : DbContext
    {
        public ProjectFinalHorus20180610020451_dbEntities()
            : base("name=ProjectFinalHorus20180610020451_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Clients_Packages> Clients_Packages { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Gift> Gifts { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Domains> Staff_Domains { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
