//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinalHorus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Domains
    {
        public int id_staff { get; set; }
        public int id_domain { get; set; }
        public bool active { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
